pipeline {
  // Agent as Docker Container
  agent {
    docker {
      image 'kalpeshmohanta/docker-node-sonar_scanner:v13'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }



  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/kalpeshmohanta/Devops_Project_2-Mern_3_Tier_App.git'
      }
    }


    stage('SonarQube Analysis') {
      steps {
        script {
          def scannerHome = tool 'sonarqube-tool'
          withSonarQubeEnv('sonarqube-server') {
            sh "${scannerHome}/bin/sonar-scanner"
          }
        }
      }
    }


    stage('Build and Push Docker Frontend Image') {
      environment {
        DOCKER_IMAGE = "kalpeshmohanta/mern-docker-compose-frontend:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "mern-docker-compose/frontend/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd mern-docker-compose/frontend && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
  



    stage('Build and Push Docker Backend Image') {
      environment {
        DOCKER_IMAGE = "kalpeshmohanta/mern-docker-compose-backend:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "mern-docker-compose/backend/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd mern-docker-compose/backend && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
    

  }
}