apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
        - name: mern-app-mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
        - name: mern-app-backend
          image: kalpeshmohanta/mern-docker-compose-backend:98
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
        - name: mern-app-frontend
          image: kalpeshmohanta/mern-docker-compose-frontend:98
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data