apiVersion: v1
kind: Service
metadata:
  name: mern-app-service
spec:
  selector:
    app: mern-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: backend
    - protocol: TCP
      port: 5173
      targetPort: 5173
      name: frontend
